### ISSUE TITLE
interactive charts

### ISSUE THREAD

**Issue by acivitillo** [acivitillo/python_data_products_workshop#39]
Code discussed during the call.

To do: we need to figure out how to display Altair chart inside a ipywidget widget.

```python
import ipywidgets as widgets
from IPython import display

class UI():
    
    def __init__(self):
        self.label = widgets.Label('Build Your Subquery')
        self.dd = widgets.Dropdown(value="hello", options=["hello", "goodbye"])
        self.dd.observe(self.callback)
        self.button = widgets.Button(description="Get Columns")
        self.out = widgets.Output()
        self.output = widgets.VBox([self.label, self.dd, self.button])
        self.button.on_click(self._btn_demo)

    def callback(self, change):
        self.label.value = str(change.owner.value)
        
    def _btn_demo(self, button):
        self.label.value = "you just pushed the button"

UI().output
```

**Comment by elubik** [comment]
I pushed altair.chart in this contructor but it throws error:
`TraitError: Element of the 'children' trait of a VBox instance must be a Widget, but a value of alt.Chart(...) <class 'altair.vegalite.v4.api.Chart'> was specified.`

As we could expect there is types mismatch because I tried to inject altair object into ipywidgets class.
I stopped at this point and did few steps back when we were struggling with altair.interactive() method. It came up that we tried this w/o parameters.
I followed [this_article](https://medium.com/@chekos/altair-and-ipywidgets-a-simple-example-f61269c72c02), downloaded [the_code](https://github.com/chekos/blog-posts/tree/master/altair%20%2B%20ipywidgets) and fixed my code.

It made my interactive charts working as expected!
I am pushing resolution to github and closing this issue.
